FROM telegraf:1.17.2

RUN apt-get update \
    && apt-get install -y rsyslog \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /var/lib/rsyslog

ADD etc/rsyslog.conf /etc/rsyslog.conf

ADD etc/entrypoint-telegraf.sh entrypoint-telegraf.sh

EXPOSE 514/tcp 514/udp

CMD /bin/sh ./entrypoint-telegraf.sh
