FROM alpine:3.12

RUN  apk update \
  && apk add rsyslog \
  && rm -rf /var/cache/apk/*

#ADD etc/rsyslog.conf /etc/rsyslog.conf

# EXPOSE 6514 6514/udp

RUN mkdir -p /var/spool/rsyslog

ENTRYPOINT [ "rsyslogd", "-n" ]
