FROM alpine:3.12

RUN  apk update \
  && apk add rsyslog \
  && rm -rf /var/cache/apk/*

#ADD etc/rsyslog.conf /etc/rsyslog.conf

#EXPOSE 514 514/udp
EXPOSE 514

# Create a group and user
RUN addgroup -S syslog && adduser -S syslog -G syslog

RUN mkdir -p /var/spool/rsyslog
RUN chown -R syslog:syslog /var/spool/rsyslog

# Tell docker that all future commands should run as the appuser user
USER syslog


ENTRYPOINT [ "rsyslogd", "-n" ]